/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    rubrics: Rubric;
    shops: Shop;
    complaints: Complaint;
    badges: Badge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    rubrics: RubricsSelect<false> | RubricsSelect<true>;
    shops: ShopsSelect<false> | ShopsSelect<true>;
    complaints: ComplaintsSelect<false> | ComplaintsSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Аватар пользователя
   */
  avatar?: (number | null) | Media;
  /**
   * Полное имя пользователя
   */
  name: string;
  /**
   * Роль определяет права доступа пользователя в системе
   */
  role: 'inspector' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Описание изображения для SEO и доступности (alt-тег)
   */
  alt?: string | null;
  /**
   * Пользователь, загрузивший этот файл
   */
  uploaded_by?: (number | null) | User;
  /**
   * IP адрес с которого была загружена медиа
   */
  ip_address?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Заголовок поста, отображается в списке и на странице
   */
  title: string;
  /**
   * Основной текст поста с форматированием
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Главное изображение поста
   */
  cover?: (number | null) | Media;
  /**
   * Одна или несколько рубрик для категоризации поста
   */
  rubrics?: (number | Rubric)[] | null;
  admin_panel?: {
    /**
     * Черновик — не виден публично. На рассмотрении — ожидает одобрения админа. Опубликовано — виден всем.
     */
    status: 'draft' | 'pending' | 'published';
    /**
     * Проставляется автоматически в момент публикации
     */
    published_at?: string | null;
    /**
     * Проставляется автоматически при создании поста
     */
    author?: (number | null) | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rubrics".
 */
export interface Rubric {
  id: number;
  /**
   * Отображаемое название рубрики
   */
  name: string;
  /**
   * URL-идентификатор рубрики, например: food-quality (только латиница, дефисы)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: number;
  /**
   * Официальное название торговой точки
   */
  store_name: string;
  /**
   * Полный адрес магазина включая город и улицу
   */
  address: string;
  /**
   * Дата фактического проведения проверки
   */
  date_checked: string;
  /**
   * Основание для проведения проверки
   */
  reason_type: 'planned' | 'complaint';
  /**
   * Содержание жалобы, послужившей основанием для проверки
   */
  complaint_text?: string | null;
  /**
   * Сумма баллов, снятых за нарушения качества (от 0 до 5). Итоговая оценка рассчитается автоматически.
   */
  quality_total_deduction?: number | null;
  /**
   * Зафиксированные факты нарушений в формате JSON-массива
   */
  quality_facts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Произвольный комментарий инспектора по разделу качества
   */
  quality_free_text?: string | null;
  /**
   * Список нарушенных нормативных статей в формате JSON-массива
   */
  quality_violated_articles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Вычисляется автоматически: 5 - штраф
   */
  quality_final_score?: number | null;
  /**
   * Отметьте, если выявлены нарушения условий хранения товаров
   */
  storage_has_violations?: boolean | null;
  /**
   * Сумма баллов, снятых за нарушения хранения (от 0 до 5). Итоговая оценка рассчитается автоматически.
   */
  storage_total_deduction?: number | null;
  /**
   * Зафиксированные факты нарушений хранения в формате JSON-массива
   */
  storage_facts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Произвольный комментарий инспектора по разделу хранения
   */
  storage_free_text?: string | null;
  /**
   * Список нарушенных нормативных статей в формате JSON-массива
   */
  storage_violated_articles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Вычисляется автоматически: 5 - штраф (если нет нарушений, автоматически 5)
   */
  storage_final_score?: number | null;
  /**
   * Вычисляется автоматически
   */
  total_score?: number | null;
  /**
   * Список выявленных преимуществ в формате JSON-массива строк
   */
  advantages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Список выявленных недостатков в формате JSON-массива строк
   */
  disadvantages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Итоговый комментарий инспектора по результатам проверки
   */
  inspector_comment?: string | null;
  /**
   * Комментарий администратора, публикуемый вместе с отчётом
   */
  final_comment?: string | null;
  /**
   * Фотографии сделанные в ходе проверки магазина
   */
  photos?:
    | {
        photo: number | Media;
        /**
         * Краткое описание того что изображено на фото
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  admin_panel?: {
    /**
     * Статус проверки отчёта администратором
     */
    status: 'pending' | 'published' | 'rejected';
    /**
     * Инспектор или редактор, создавший отчёт
     */
    created_by?: (number | null) | User;
    /**
     * Была ли ранее проведена проверка этого магазина
     */
    prev_check_status?: ('never' | 'done') | null;
    /**
     * Дата предыдущей проверки этого магазина
     */
    last_check_date?: string | null;
    /**
     * Общее количество проверок магазина за всё время
     */
    total_checks_count?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints".
 */
export interface Complaint {
  id: number;
  admin_panel?: {
    /**
     * IP адрес с которого была подана жалоба
     */
    ip_address?: string | null;
    /**
     * Текущий статус рассмотрения жалобы администратором
     */
    status?: ('new' | 'in_progress' | 'closed') | null;
    /**
     * Внутренняя заметка для администраторов, не видна заявителю
     */
    admin_note?: string | null;
  };
  /**
   * Адрес магазина, на который подаётся жалоба
   */
  store_address: string;
  /**
   * Можно выбрать несколько типов нарушений
   */
  problem_types: ('expired_products' | 'poor_quality' | 'storage_violation' | 'unsanitary' | 'other')[];
  /**
   * Укажите дату в свободной форме, например: 12 мая 2025
   */
  problem_date: string;
  /**
   * Была ли попытка решить проблему на месте через персонал магазина
   */
  staff_contacted: 'yes' | 'no';
  /**
   * Подробное описание нарушения в свободной форме
   */
  description: string;
  /**
   * Фотографии подтверждающие факт нарушения. Файлы необходимо загрузить заранее через /api/media
   */
  photos?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  /**
   * Введите код строго в формате из регламента (например: #P01-ASTR)
   */
  code: string;
  type: 'P' | 'YOU';
  ownerName?: (number | null) | User;
  status?: ('active' | 'revoked' | 'lost') | null;
  /**
   * Служебная заметка администратора (например: выдан 05.06.2026)
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'rubrics';
        value: number | Rubric;
      } | null)
    | ({
        relationTo: 'shops';
        value: number | Shop;
      } | null)
    | ({
        relationTo: 'complaints';
        value: number | Complaint;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploaded_by?: T;
  ip_address?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  cover?: T;
  rubrics?: T;
  admin_panel?:
    | T
    | {
        status?: T;
        published_at?: T;
        author?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rubrics_select".
 */
export interface RubricsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  store_name?: T;
  address?: T;
  date_checked?: T;
  reason_type?: T;
  complaint_text?: T;
  quality_total_deduction?: T;
  quality_facts?: T;
  quality_free_text?: T;
  quality_violated_articles?: T;
  quality_final_score?: T;
  storage_has_violations?: T;
  storage_total_deduction?: T;
  storage_facts?: T;
  storage_free_text?: T;
  storage_violated_articles?: T;
  storage_final_score?: T;
  total_score?: T;
  advantages?: T;
  disadvantages?: T;
  inspector_comment?: T;
  final_comment?: T;
  photos?:
    | T
    | {
        photo?: T;
        caption?: T;
        id?: T;
      };
  admin_panel?:
    | T
    | {
        status?: T;
        created_by?: T;
        prev_check_status?: T;
        last_check_date?: T;
        total_checks_count?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints_select".
 */
export interface ComplaintsSelect<T extends boolean = true> {
  admin_panel?:
    | T
    | {
        ip_address?: T;
        status?: T;
        admin_note?: T;
      };
  store_address?: T;
  problem_types?: T;
  problem_date?: T;
  staff_contacted?: T;
  description?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  ownerName?: T;
  status?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Глобальные настройки сайта, доступные только администраторам. Пока все что описано здесь нигде не используется, но в будущем может пригодиться для хранения различных параметров и конфигураций. Make FreshCheck Great Again!
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Отображается в заголовке браузера и шапке сайта
   */
  site_name: string;
  /**
   * Краткое описание для SEO (meta description)
   */
  site_description?: string | null;
  /**
   * Основной логотип сайта
   */
  logo?: (number | null) | Media;
  /**
   * Иконка сайта в браузере
   */
  favicon?: (number | null) | Media;
  /**
   * Публичный email для обращений
   */
  contact_email?: string | null;
  /**
   * Контактный телефон в формате +7 (999) 000-00-00
   */
  contact_phone?: string | null;
  /**
   * Физический адрес организации
   */
  address?: string | null;
  /**
   * Например: Пн–Пт с 9:00 до 18:00
   */
  working_hours?: string | null;
  /**
   * Ссылка на страницу ВКонтакте
   */
  social_vk?: string | null;
  /**
   * Ссылка на Telegram-канал или бот
   */
  social_telegram?: string | null;
  /**
   * Ссылка на YouTube-канал
   */
  social_youtube?: string | null;
  /**
   * Через запятую, для meta keywords
   */
  seo_keywords?: string | null;
  /**
   * Например: G-XXXXXXXXXX
   */
  google_analytics_id?: string | null;
  /**
   * Числовой идентификатор счётчика Метрики
   */
  yandex_metrika_id?: string | null;
  /**
   * На этот адрес будут приходить уведомления о новых жалобах
   */
  notification_email?: string | null;
  /**
   * Токен бота для отправки уведомлений в Telegram
   */
  telegram_bot_token?: string | null;
  /**
   * ID чата или канала куда бот отправляет уведомления
   */
  telegram_chat_id?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site_name?: T;
  site_description?: T;
  logo?: T;
  favicon?: T;
  contact_email?: T;
  contact_phone?: T;
  address?: T;
  working_hours?: T;
  social_vk?: T;
  social_telegram?: T;
  social_youtube?: T;
  seo_keywords?: T;
  google_analytics_id?: T;
  yandex_metrika_id?: T;
  notification_email?: T;
  telegram_bot_token?: T;
  telegram_chat_id?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}